#-----------------------------------------------------------------
# Raven Properties file Template. Created by Raven v3.8.1 w/ netCDF
#-----------------------------------------------------------------
# Raven Input file
# GEM-Hydro SE region
#-----------------------------------------------------------------

#-----------------------------------------------------------------
# Soil Classes
#-----------------------------------------------------------------
:SoilClasses
  :Attributes,
  :Units,
    AQUIFER      # only one soil class used here  
:EndSoilClasses

#-----------------------------------------------------------------
# Land Use Classes
#-----------------------------------------------------------------
:LandUseClasses, 
       :Attributes,        IMPERM,    FOREST_COV, 
            :Units,          frac,          frac, 
  Landuse_Land_HRU,             0,             1, 
              LAKE,             0,             0,     
:EndLandUseClasses

#-----------------------------------------------------------------
# Vegetation Classes
#-----------------------------------------------------------------
:VegetationClasses, 
     :Attributes,        MAX_HT,       MAX_LAI, MAX_LEAF_COND, 
          :Units,             m,          none,      mm_per_s, 
    Veg_Land_HRU,            25,           5.0,           5.0, 
            LAKE,             0,             0,             0,        
:EndVegetationClasses

#-----------------------------------------------------------------
# Soil Profiles
#-----------------------------------------------------------------
:SoilProfiles
    Soil_Land_HRU,     1,       AQUIFER,   5
             LAKE,     1,       AQUIFER,   5
:EndSoilProfiles

#-----------------------------------------------------------------
# Global Parameters
#-----------------------------------------------------------------
:AvgAnnualRunoff   486.9
:GlobalParameter            RAINSNOW_TEMP    0.0
:GlobalParameter           TOC_MULTIPLIER    1.0
:GlobalParameter   TIME_TO_PEAK_MULTIPLIER   1.0 
:GlobalParameter   GAMMA_SHAPE_MULTIPLIER    1.0
:GlobalParameter   GAMMA_SCALE_MULTIPLIER    1.0

#-----------------------------------------------------------------
# Soil Parameters
#-----------------------------------------------------------------
:SoilParameterList
  :Parameters,        POROSITY,    PET_CORRECTION,       MAX_BASEFLOW_RATE,      BASEFLOW_N, BASEFLOW_THRESH, 
       :Units,            none,                 -,                    mm/d,            none,            none, # (units not generated by .rvp template)
    [DEFAULT],             0.2,                 0,                   29.32,            1.46,           0.649, 
      AQUIFER,             0.2,                 0,     %MAX_BASEFLOW_RATE%,    %BASEFLOW_N%,             0.6, 
:EndSoilParameterList

#-----------------------------------------------------------------
# Land Use Parameters
#-----------------------------------------------------------------
:LandUseParameterList
          :Parameters,    LAKE_PET_CORR,    WIND_VEL_CORR,     RELHUM_CORR,     FOREST_SPARSENESS, 
               :Units,                -,                -,               -,                     -, # (units not generated by .rvp template)
            [DEFAULT],              0.0,              0.0,             0.0,                   0.0, 
     Landuse_Land_HRU,              0.0,              0.0,             0.0,                   0.0, 
                 LAKE,              0.0,              0.0,             0.0,                   0.0, 
:EndLandUseParameterList

#-----------------------------------------------------------------
# Vegetation Parameters
#-----------------------------------------------------------------
:VegetationParameterList
  :Parameters,       SAI_HT_RATIO, 
          :Units,               -, # (units not generated by .rvp template)
       [DEFAULT],             0.0, 
    Veg_Land_HRU,             0.0, 
            LAKE,             0.0,
:EndVegetationParameterList

:SeasonalRelativeLAI
    Veg_Land_HRU, 0.2,0.2,0.2,0.4,0.8,1,1,0.7,0.6,0.0.3,0.0.2,0.0.2
    LAKE, 0,0,0,0,0,0,0,0,0,0,0,0  
:EndSeasonalRelativeLAI

:SeasonalRelativeHeight
    Veg_Land_HRU, 1,1,1,1,1,1,1,1,1,1,1,1
    LAKE, 0,0.0,0.0,0,0,0,0,0,0,0,0,0
:EndSeasonalRelativeHeight

# redirects to channel properties file
:RedirectToFile         channel_properties.rvp